services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    volumes:
      - ./server/src/data/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  server:
    build: ./server
    container_name: graphql_server
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/eventdb
    ports:
      - "4000:4000"
    depends_on:
      - db
